export {
  getMembers,
  insertMember,
  updateMember,
  deleteMember,
  getNews,
  insertNews,
  updateNews,
  deleteNews,
  getMinutes,
  getNextAtaNumber,
  insertMinute,
  updateMinute,
  deleteMinute,
  getCalendarEvents,
  insertCalendarEvent,
  updateCalendarEvent,
  deleteCalendarEvent,
  getNextCalendarEvent,
  getUpcomingCalendarActivities,
  getFinanceEntries,
  insertFinanceEntry,
  updateFinanceEntry,
  deleteFinanceEntry,
  getFinanceReceipts,
  insertFinanceReceipt,
  deleteFinanceReceipt,
  deleteFinanceReceiptsForEntry,
  downloadFinanceReceiptFile,
  FINANCE_RECEIPTS_BUCKET,
  getRollCalls,
  getRollCallByDate,
  getRollCallsByYearAndGestao,
  upsertRollCall,
  getCandidates,
  insertCandidate,
  updateCandidate,
  deleteCandidate,
  getCandidateDocuments,
  getCandidateDocumentByType,
  upsertCandidateDocument,
  deleteCandidateDocument,
  downloadCandidateDocumentFile,
  CANDIDATE_DOCUMENTS_BUCKET,
} from './supabase-data';

export function generateId() {
  return `id-${Date.now()}-${Math.random().toString(36).slice(2, 11)}`;
}
